#%RAML 1.0
title: NamedExample used in example facet

types:
  one:
    type: object
    properties:
      prop1:
        type: string
      prop2:
        type: integer
    examples: !include named-example-fragment.raml