#%RAML 1.0
title: test-hackathon-cases
protocols: [ HTTP ]
mediaType: [application/json]
types:
  bar:
    type: string
    #facets:
    #xml:

/test:
  get:
    queryParameters:
      asd:
        required: as
        

    
    