#%RAML 1.0
title: Mandatory payload
/test:
  get:
    body:
      application/json:
        type: object
        example:
          some: somesome
        additionalProperties: true
        properties:
          some:
            type: string
            required: true
  post:
    body:
      application/xml:
        type: object
        example: <schema><someOther>someString</someOther></schema>
        additionalProperties: true
        properties:
          someOther:
            type: string
            required: true
